[build-system]

requires = [
   "setuptools",
   "wheel"
]

build-backend = "setuptools.build_meta"

[project]
name="swellpy"
version="0.0.1"
dependencies = [
   "requests",
   "requests-toolbelt",
   "ratelimit"
]